### PR TITLE
Test run detail page

### PR DESCRIPTION
**Pull request by whuiras**
added detail page

### CODE REVIEW

**Review by dwagg — CHANGES_REQUESTED** [review]
Can we make the UITextViews so that they cannot be edited, either programmatically in TestStepViewController or in the Main.storyboard.

**Review by cdevan — CHANGES_REQUESTED** [review]
Besides the change requested by David, I think the text for all the pass/fail/block buttons we've added in the last sprint needs to be bolded and larger - it's very small, especially on the iPhone 7.

**Review by dwagg — APPROVED** [review]
The changes that I asked for seem to be fixed.

**Review by cdevan — APPROVED** [review]

**Review by dwagg — CHANGES_REQUESTED** [review]
What are the "TestRunIndexViewController 2" and "TestStepTableViewCell 2"? I don't understand what those files are.

**Review by dwagg — APPROVED** [review]

**Pull request merged**
