### PR TITLE
Added action sheet options for photo taking and removal

### PR DESCRIPTION
**Pull request by mmcbee1**
...If this is something we want.

### CODE REVIEW

**Comment by mmcbee1** [comment]
This is just a quick version of this functionality to see if we like it - it didn't take too long so if we use the other view we can discard this branch. Things that need to be addressed if we use this branch:

- Orange X is probably not ideal, need to change so whatever we chose can be seen on all background colors
- "noimage.jpg" needs to be updated with something that we make that is free for commercial use, this was just a placeholder to show how it might look
- Needs to be tested on a phone
- Currently has no unit/UI tests

**Comment by JasonRitz** [comment]
When selecting "view image" it shows the oldest image attached to the run, not the most current. So if the user uploads a photo then selects "view image" they don't see their photo. 

"remove this image" does not remove the image from the Jama web app just the local run to be submitted. 

I think we need to add a "uploading image" popup for the duration of the upload. Right now when I take a picture and hit submit, while it is uploading (3 to 5 sec) I can still click on things and make changes to the run. 

I tested using the Demo user and UAV Sample set/Integrated Testing/Lots of runs/Standard-sized screwdriver. You can look at the run on the web to see the photos I uploaded to it. All testing was done on my iPhone 6

**Comment by mmcbee1** [comment]
Thank you for your feedback. A couple thoughts:

> When selecting "view image" it shows the oldest image attached to the run, not the most current. So if the user uploads a photo then selects "view image" they don't see their photo.

Just from looking at the code I'm not sure why this would be the case, but since I have no way to test this on my phone I'm not sure how to go about fixing it. Maybe this is a side effect of the camera upload taking a few seconds? Do you have any suggestions?

> "remove this image" does not remove the image from the Jama web app just the local run to be submitted.

This was the intention - maybe we should change the wording to be "remove image from this run submission" or something similar? Removing an image that was previously uploaded will only be possible for in progress runs, and I think in order to have the image locally we'll need to update our test run model and the API calls to also pull out and store the image. I feel like this is significant enough that it should be its own ticket.

> I think we need to add a "uploading image" popup for the duration of the upload. Right now when I take a picture and hit submit, while it is uploading (3 to 5 sec) I can still click on things and make changes to the run.

This makes sense, but I feel like this is also enough of a change that it could be its own ticket - maybe for someone who's done a popup ticket before and knows it well enough to implement it quickly? I'm not sure I will have enough time to finish these changes within our time frame, while also allowing for testing and review.

**Review by JasonRitz — APPROVED** [review]
code is good, passes all tests, functions as expected. Great job!!!

**Pull request merged**
