### PR TITLE
Change screen title labels so that all of them are fixed size font an…

### PR DESCRIPTION
**Pull request by dwagg**
…d will truncate if need be. Also renamed a bunch of no name views for clarity and unity.

### CODE REVIEW

**Comment by dwagg** [comment]
screen shot 2017-08-13 at 6 54 17 pm
New side by side

**Comment by dwagg** [comment]
Included in this branch is renaming of a bunch of views in the storyboard, so you will see those. I tried to make it so you wouldn't need to click though 3-4 different views all named "view". Also I made the title label on the Project screen and Test List Accordion Screen also have fixed font size, truncating tails. They are a predefined string which always fits but I figured better to be consistent. Also I changed the color of the Projects title label "Choose a project to view" from a really dark blue to the default black like the other screens have.

**Comment by mmcbee1** [comment]
Can we add a little padding to the text - maybe with a leading/trailing margin to the label? With long titles the text is very close to the sides of the screen. I would bet 2-3 will be enough to feel more balanced.

**Review by mmcbee1 — CHANGES_REQUESTED** [review]
Added a comment about the label margin, but otherwise looks good. Travis is cool with it and it's up to date with master.

**Review by mmcbee1 — APPROVED** [review]

**Comment by mmcbee1** [comment]
Looks good, addressed acceptance criteria and feedback, up to date with master and passes Travis' checks. Good to merge!

**Pull request merged**
